
on:
  issue_comment:
    types: [created]
name: Autosquash
jobs:
  autosquash:
    name: Autosquash
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/autosquash')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Autosquash
      uses: mgreenw/autosquash@max/executable-autosqaush
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
